version: '3.8'

services:
  web:
    build: .
    # Remove the ports section - Coolify will handle this
    environment:
      - FLASK_CONFIG=development
      - DATABASE_URL=postgresql://survey_user:survey_password@db:5432/survey_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "
        flask db upgrade || (flask db init && flask db migrate -m 'Initial migration' && flask db upgrade) &&
        python run.py
      "

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=survey_db
      - POSTGRES_USER=survey_user
      - POSTGRES_PASSWORD=survey_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # No ports section needed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U survey_user -d survey_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: